### ISSUE TITLE
Trying to change the sender name to company name 

### ISSUE THREAD

**Issue by baselka** [nexmo-community/nexmo-php-quickstart#25]
I was trying to change the sender name wherein the receiver should see the company name instead of INFO or NXSMS but it did not work .
is it possible ? by changing the the value of From => 'Company Name' !
or there is a specific configuration .
thanks

**Comment by mheap** [comment]
@baselka This is possible, but there are limitations based on the country you're sending a message to. You can search the [Nexmo Knowledge Base](https://help.nexmo.com/hc/en-us) for the country you're sending to for more information

**Comment by baselka** [comment]
thanks @mheap
